### ISSUE TITLE
Adjustment layer detected as pixel

### ISSUE THREAD

**Issue by cornelg7** [psd-tools/psd-tools#337] opened 2022-10-20 12:50 UTC
**Describe the bug**
I have an Adjustment layer that adjusts the Hue / Saturation. If I loop through all the layers, the kind of this adjustment layer is 'pixel' instead of 'huesaturation'.

**To Reproduce**

I have the following layer structure:
![image](https://user-images.githubusercontent.com/13762182/196953440-7ef63e7c-1184-4904-a616-901104feebe9.png)

When I loop through the layers, the kind is pixel for the adjustment layer:

```python
psd = PSDImage.open('filename.psd')
for layer in psd:
    print(f'{layer.name} - {layer.kind}')
```
Output is:
```
mockup-foreground - pixel
Hue/Saturation - pixel
images - group
mockup-background - pixel
```

**Expected behavior**
Output should be
```
mockup-foreground - pixel
Hue/Saturation - huesaturation
images - group
mockup-background - pixel
```

**Environment**
 - Python [3.7]
 - Version [v1.9.23]

**Additional context**

The PSD file is created via [photopea.com](https://www.photopea.com/)

**Comment by dario-spagnolo** [comment] 2024-04-30 09:04
Duplicate of #338 
Should be fixed by PR #399

**Closed** 2024-05-01 04:48 UTC
Labels: bug
